version: "3.3"
services:
  savivaldybes:
    build: . 
    restart: always
    ports:
      - 8789:8080
    volumes:
      - ./geoserver/data_dir:/usr/app/data_dir
    environment:
      POSTGRES_PASSWORD: "a010o8h84pk67510o8h"
      POSTGRES_USER: "admin"
